/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenericApiResponse } from './genericApiResponse';
import { GetAILabelingConfigResponseAllOf } from './getAILabelingConfigResponseAllOf';

export class GetAILabelingConfigResponse {
    /**
    * Whether the operation succeeded
    */
    'success': boolean;
    /**
    * Optional error description (set if \'success\' was false)
    */
    'error'?: string;
    'dataPreviewCategory': GetAILabelingConfigResponseDataPreviewCategoryEnum;
    'dataWithoutMetadataKey'?: string;
    'maxDataPreviewCount': number;
    'lastUsedTransformationBlockId'?: number;
    'lastUsedParameters'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "dataPreviewCategory",
            "baseName": "dataPreviewCategory",
            "type": "GetAILabelingConfigResponseDataPreviewCategoryEnum"
        },
        {
            "name": "dataWithoutMetadataKey",
            "baseName": "dataWithoutMetadataKey",
            "type": "string"
        },
        {
            "name": "maxDataPreviewCount",
            "baseName": "maxDataPreviewCount",
            "type": "number"
        },
        {
            "name": "lastUsedTransformationBlockId",
            "baseName": "lastUsedTransformationBlockId",
            "type": "number"
        },
        {
            "name": "lastUsedParameters",
            "baseName": "lastUsedParameters",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return GetAILabelingConfigResponse.attributeTypeMap;
    }
}


export type GetAILabelingConfigResponseDataPreviewCategoryEnum = 'allData' | 'unlabeledData' | 'dataWithoutMetadataKey';
export const GetAILabelingConfigResponseDataPreviewCategoryEnumValues: string[] = ['allData', 'unlabeledData', 'dataWithoutMetadataKey'];
