/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenericApiResponse } from './genericApiResponse';
import { WindowSettings } from './windowSettings';
import { WindowSettingsResponseAllOf } from './windowSettingsResponseAllOf';

export class WindowSettingsResponse {
    /**
    * Whether the operation succeeded
    */
    'success': boolean;
    /**
    * Optional error description (set if \'success\' was false)
    */
    'error'?: string;
    'windowSettingsEvent': Array<WindowSettings>;
    'windowSettingsContinuous': Array<WindowSettings>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "windowSettingsEvent",
            "baseName": "windowSettingsEvent",
            "type": "Array<WindowSettings>"
        },
        {
            "name": "windowSettingsContinuous",
            "baseName": "windowSettingsContinuous",
            "type": "Array<WindowSettings>"
        }    ];

    static getAttributeTypeMap() {
        return WindowSettingsResponse.attributeTypeMap;
    }
}

